tasks:
# - init: pip install -r requirements.txt
  - command: gp open "Pyspark 101 Statistical Seminars.ipynb" 

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers